#!/usr/bin/env bash
# This script reads from /etc/passwd and
# displays the username, user id, and home directory
# for each user.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"