#!/usr/bin/env bash
# displays numbers from 1 to 20, but for multiples of 4, 9, and 17, 
##  displays a message.
# 4 displays "bad luck from China"
# 9 displays "bad luck from Japan"
# 17 displays "bad luck from Italy"

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done