#!/usr/bin/env bash
# This script is displaying the second field of the 
#   file names in the current directory. 
#   The file names are formatted as follows:
#   -<file_name>
#   The script must display the second field of the file names.
#   The script must only display the second field.

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done